# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rneves-s <rneves-s@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/27 18:48:49 by rneves-s          #+#    #+#              #
#    Updated: 2023/05/27 22:03:20 by rneves-s         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS				=	actions/index_pushb.c

OBJS				=	$(SRCS:.c=.o)

CC					= 	gcc
RM					= 	rm -f
CFLAGS				=	-Wall -Wextra -Werror -I

NAME				= push_swap.a

all:				$(NAME)

$(NAME): $(SRCS) $(OBJS) mondatory/push_swap.h
	@gcc $(CFLAGS) $(SRCS) -o $(NAME)
	@echo ------Compiled Mondatory part-------

clean:				
					$(RM) $(OBJS)

fclean:				clean
					$(RM) $(NAME)

re:					fclean $(NAME)

.PHONY:			all clean fclean re
