# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rneves-s <rneves-s@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/15 18:31:36 by rneves-s          #+#    #+#              #
#    Updated: 2023/04/15 19:46:02 by rneves-s         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS				=	actions/push.c actions/reverse.c actions/rotate.c actions/swap.c \
						validators/check_is_numbers.c \
						push_swap.c

OBJS				=	$(SRCS:.c=.o)

CC					= 	gcc
RM					= 	rm -f
CFLAGS				=	-Wall -Wextra -Werror -I

all:				$(NAME)